### ISSUE TITLE
Clarification of comment in entrypoint.sh

### ISSUE THREAD

**Issue by KoenDG** [sudo-bmitch/jenkins-docker#3]
I ran into this repo while reading an answer on stackoverflow.

Reading up on the entrypoint.sh file, I'm a bit confused by this statement:

`# drop access to jenkins user`

At first I thought it mean taking away the Jenkins user's permissions, but in context of what gosu does and the fact that root was set as user in the Dockerfile, it sounds more like "drop access from user root to user jenkins".

Is that right? I find the wording a bit confusing.

**Comment by sudo-bmitch** [comment]
Your understanding is correct, it is dropping from the root user to the jenkins user.

**Comment by KoenDG** [comment]
Ok, I created a PR for it, #4

**Comment by sudo-bmitch** [comment]
Thanks. I've merged it. Hopefully that reduces confusion for others.
