### ISSUE TITLE
Data volume source

### ISSUE THREAD

**Issue by jmunozco** [sudo-bmitch/jenkins-docker#9]
Where can I find the data folder that is mounted as jenkins-home that is the Jenkins persistent data? I want to remove it and start from zero, but I can't find it. Thanks

**Comment by sudo-bmitch** [comment]
Named volumes are managed with `docker volume`. You can use `docker volume ls` to find the volume with the project/stack name prepended. And `docker volume rm` to delete a named volume that is not currently in use.
